
'use client';

import { useState, useMemo } from 'react';
import { useLanguage } from '@/hooks/use-language';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert';
import { Loader2, Search, X, Pill, Info, ShieldAlert, Sparkles, Utensils, Clock, Languages, AlertTriangle } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';

export type GetMedicineInfoOutput = {
  isMedicine: boolean;
  medicineName: string;
  whatItIs: string;
  usage: string;
  foodInstructions: string;
  timeTaken: string;
  sideEffects: string[];
  localSummary: string;
};

export default function SearchMedicinePage() {
  const { getTranslation, language } = useLanguage();
  const [searchTerm, setSearchTerm] = useState('');
  const [isSearching, setIsSearching] = useState(false);
  const [selectedDrugInfo, setSelectedDrugInfo] = useState<GetMedicineInfoOutput | null>(null);
  const [error, setError] = useState<string | null>(null);
  const { toast } = useToast();

  const handleSearch = async () => {
    if (searchTerm.length < 2) {
      setSelectedDrugInfo(null);
      setError(null);
      return;
    }
    setIsSearching(true);
    setSelectedDrugInfo(null);
    setError(null);

    try {
      const response = await fetch('/api/medicine-search', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ searchTerm, language }),
      });

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || getTranslation(translations.searchFailed));
      }
      
      const result: GetMedicineInfoOutput = await response.json();

      if (result.isMedicine) {
        setSelectedDrugInfo(result);
      } else {
        setError(getTranslation(translations.notAMedicine));
      }
    } catch (err) {
      console.error(err);
      const errorMessage = (err as Error).message || getTranslation(translations.searchFailed);
      setError(errorMessage);
      toast({
        variant: 'destructive',
        title: 'Search Error',
        description: errorMessage,
      });
    } finally {
      setIsSearching(false);
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === 'Enter') {
      handleSearch();
    }
  };

  const handleClearSearch = () => {
    setSearchTerm('');
    setSelectedDrugInfo(null);
    setError(null);
  };

  const translations = useMemo(
    () => ({
      title: { en: 'Search Medicine', am: 'መድሃኒት ይፈልጉ', om: 'Qoricha Barbaadi' },
      description: {
        en: 'Enter a medicine name to get AI-powered information.',
        am: 'በAI የተደገፈ መረጃ ለማግኘት የመድሃኒት ስም ያስገቡ።',
        om: 'Odeeffannoo AI-tiin deeggarame argachuuf maqaa qorichaa galchi.',
      },
      searchPlaceholder: {
        en: 'Type a medicine name...',
        am: 'የመድሃኒት ስም ይተይቡ...',
        om: 'Maqaa qorichaa barreessi...',
      },
      searchButton: { en: 'Search', am: 'ፈልግ', om: 'Barbaadi' },
      notAMedicine: { en: 'This does not seem to be a valid medicine. Please try another name.', am: 'ይህ ትክክለኛ መድሃኒት አይመስልም። እባክዎ ሌላ ስም ይሞክሩ።', om: 'Kun qoricha sirrii fakkaatu miti. Maaloo maqaa biraa yaali.' },
      searchFailed: { en: 'An error occurred during the search. Please try again.', am: 'በፍለጋ ወቅት ስህተት ተፈጥሯል። እባክዎ እንደገና ይሞክሩ።', om: 'Yeroo barbaachaatti dogoggorri uumameera. Maaloo irra deebi\'ii yaali.' },
      disclaimer: { en: 'This is for informational purposes only. Always consult a doctor or pharmacist before taking any medication.', am: 'ይህ ለመረጃ አገልግሎት ብቻ ነው። ማንኛውንም መድሃኒት ከመውሰድዎ በፊት ሁል ጊዜ ሐኪም ወይም ፋርማሲስት ያማክሩ።', om: 'Kun odeeffannoof qofa. Qoricha kamiyyuu fudhachuu keessan dura yeroo hunda hakiima yookiin faarmaasii mariisisaa.' },
      generatingInfo: { en: 'AI is generating information for', am: 'AI መረጃ እያመነጨ ነው ለ', om: 'AI odeeffannoo uumaa jira' },
      whatItIs: { en: 'What it is', am: 'ምንድን ነው', om: 'Maali Inni' },
      usage: { en: 'Usage', am: 'አጠቃቀም', om: 'Fayyadama' },
      foodInstructions: { en: 'Food Instructions', am: 'የምግብ መመሪያ', om: 'Qajeelfama Nyaataa' },
      timeTaken: { en: 'Time Taken', am: 'የሚወስድበት ጊዜ', om: 'Yeroo Fudhatamu' },
      sideEffects: { en: 'Side Effects', am: 'የጎንዮሽ ጉዳቶች', om: 'Miidhaa Ganaa' },
      localSummary: { en: 'Summary', am: 'ማጠቃለያ', om: 'Cuunfaa' },
      aiSummaryFor: { en: 'AI-Generated Summary for', am: 'በAI የተፈጠረ ማጠቃለያ ለ', om: 'Cuunfaa AI-iin Uumameef' },
      generatedBy: { en: 'Information generated by IDA Health Assistant.', am: 'በIDA ጤና ረዳት የተፈጠረ መረጃ።', om: 'Odeeffannoo Gargaaraa Fayyaa IDA tiin uumame.' },
      disclaimerTitle: { en: 'Disclaimer', am: 'የኃላፊነት ማስተባበያ', om: 'Of-gaafii' },
    }),
    [getTranslation]
  );

  return (
    <div className="p-4 md:p-6 space-y-6">
      <header>
        <h1 className="font-headline text-4xl">{getTranslation(translations.title)}</h1>
        <p className="text-muted-foreground">{getTranslation(translations.description)}</p>
      </header>

      <div className="relative">
        <Search className="absolute left-3 top-1/2 -translate-y-1/2 h-5 w-5 text-muted-foreground" />
        <Input
          placeholder={getTranslation(translations.searchPlaceholder)}
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          onKeyDown={handleKeyDown}
          className="pl-10 pr-20 text-lg h-14"
        />
        {searchTerm && !isSearching && (
          <Button variant="ghost" size="icon" className="absolute right-16 top-1/2 -translate-y-1/2" onClick={handleClearSearch}>
            <X className="h-5 w-5 text-muted-foreground" />
          </Button>
        )}
         <Button onClick={handleSearch} disabled={isSearching} className="absolute right-2 top-1/2 -translate-y-1/2 h-10">
            {isSearching ? <Loader2 className="h-5 w-5 animate-spin" /> : getTranslation(translations.searchButton)}
        </Button>
      </div>

      {isSearching && (
        <Card className="flex flex-col items-center justify-center p-8 text-center space-y-4">
          <Sparkles className="h-10 w-10 animate-pulse text-primary" />
          <p className="font-semibold text-muted-foreground">{getTranslation(translations.generatingInfo)} "{searchTerm}"...</p>
        </Card>
      )}

      {error && (
        <Alert variant="destructive">
          <AlertTriangle className="h-4 w-4" />
          <AlertTitle>{error}</AlertTitle>
        </Alert>
      )}

      {selectedDrugInfo && (
        <DrugInfoDisplay 
          drugInfo={selectedDrugInfo} 
          translations={translations}
        />
      )}
    </div>
  );
}

function DrugInfoDisplay({ drugInfo, translations }: { drugInfo: GetMedicineInfoOutput, translations: any }) {
  const { whatItIs, usage, foodInstructions, timeTaken, sideEffects, localSummary, medicineName } = drugInfo;
  const { getTranslation } = useLanguage();

  const sections = [
    { title: getTranslation(translations.whatItIs), content: whatItIs, icon: Pill },
    { title: getTranslation(translations.usage), content: usage, icon: Info },
    { title: getTranslation(translations.foodInstructions), content: foodInstructions, icon: Utensils },
    { title: getTranslation(translations.timeTaken), content: timeTaken, icon: Clock },
  ];

  return (
    <Card className='animate-in fade-in-50'>
      <CardHeader>
        <CardTitle className="font-headline text-2xl flex items-center gap-2">
            <Sparkles className="text-primary"/> {getTranslation(translations.aiSummaryFor)} "{medicineName}"
        </CardTitle>
        <CardDescription>{getTranslation(translations.generatedBy)}</CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        {sections.map((section, index) => (
            <InfoSection 
                key={index}
                title={section.title}
                content={section.content}
                icon={section.icon}
            />
        ))}

        <InfoSection 
            title={getTranslation(translations.sideEffects)}
            content={
                <ul className='list-disc pl-5 space-y-1'>
                    {sideEffects.map((effect, i) => <li key={i}>{effect}</li>)}
                </ul>
            }
            icon={ShieldAlert}
        />
        
        <div className='p-4 bg-muted/50 rounded-lg space-y-4'>
            <InfoSection 
                title={getTranslation(translations.localSummary)}
                content={
                    <div className='space-y-2'>
                        <p>{localSummary}</p>
                    </div>
                }
                icon={Languages}
            />
        </div>
        
        <Alert variant="default" className="mt-4 border-amber-500 bg-amber-50 dark:bg-amber-950">
            <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400" />
            <AlertTitle className="text-amber-800 dark:text-amber-300">{getTranslation(translations.disclaimerTitle)}</AlertTitle>
            <AlertDescription className="text-amber-700 dark-text-amber-500">
                {getTranslation(translations.disclaimer)}
            </AlertDescription>
        </Alert>

      </CardContent>
    </Card>
  )
}

function InfoSection({ title, content, icon: Icon }: { title: string; content: React.ReactNode; icon?: React.ElementType }) {
  return (
    <div className="flex items-start gap-4">
        {Icon && (
            <div className="p-2 bg-muted rounded-full mt-1">
                <Icon className="h-5 w-5 text-primary" />
            </div>
        )}
        <div className='flex-1'>
            <h3 className="font-bold text-foreground text-lg">{title}</h3>
            <div className="text-md text-muted-foreground">{content}</div>
        </div>
    </div>
  );
}
