'use client';

import { useState, useRef, useMemo, useEffect } from 'react';
import Image from 'next/image';
import { Button } from '@/components/ui/button';
import { Camera, Upload, X, Wand2, AlertTriangle, ShieldCheck, CheckCircle, XCircle, Info } from 'lucide-react';
import { useToast } from '@/hooks/use-toast';
import { Card, CardContent, CardHeader, CardTitle, CardDescription } from '@/components/ui/card';
import { Alert, AlertTitle, AlertDescription } from '@/components/ui/alert';
import { useLanguage } from '@/hooks/use-language';
import './scan-animation.css';

type AnalyzeMedicinePackageOutput = {
  name: string;
  usage: string;
  pros: string;
  cons: string;
};

// New mock data for Myaderm CBD Pain Cream
const demoResultEn: AnalyzeMedicinePackageOutput = {
  name: 'Myaderm CBD Pain Cream',
  usage: 'Apply a thin layer to the affected area no more than 3 to 4 times daily. Rub gently and thoroughly. After applying, wash your hands unless you are using the cream to treat the hands.',
  pros: 'Provides targeted, temporary relief from minor aches and pains of muscles and joints. It is THC-free and absorbs quickly into the skin for fast-acting effects.',
  cons: 'For external use only. Do not use on wounds or damaged skin. Avoid contact with eyes. Stop use and ask a doctor if condition worsens or symptoms persist for more than 7 days.',
};

const demoResultAm: AnalyzeMedicinePackageOutput = {
    name: 'ማያደርም ሲቢዲ የህመም ማስታገሻ ክሬም',
    usage: 'በተጎዳው አካባቢ ላይ በቀን ከ3 እስከ 4 ጊዜ ያልበለጠ ስስ ሽፋን ይቀቡ። በቀስታ እና በደንብ ይሹት። ከተቀቡ በኋላ፣ ክሬሙን ለእጅ ህክምና ካልተጠቀሙበት በስተቀር እጅዎን ይታጠቡ።',
    pros: 'ለትንሽ የጡንቻ እና የመገጣጠሚያ ህመሞች ያነጣጠረ፣ ጊዜያዊ እፎይታ ይሰጣል። ከTHC ነፃ ሲሆን ለፈጣን ውጤት በፍጥነት ወደ ቆዳ ውስጥ ይገባል።',
    cons: 'ለዉጪ ጥቅም ብቻ። በቁስሎች ወይም በተጎዳ ቆዳ ላይ አይጠቀሙ። ከዓይኖች ጋር ንክኪን ያስወግዱ። ሁኔታው ከተባባሰ ወይም ምልክቶቹ ከ7 ቀናት በላይ ከቀጠሉ መጠቀሙን ያቁሙና ሐኪም ያማክሩ።',
};

const demoResultOm: AnalyzeMedicinePackageOutput = {
    name: 'Myaderm CBD Muccaa Dhukkubbii',
    usage: 'Guyyaatti yeroo 3 hanga 4 caalaa bakka miidhame irratti haphiistee dibi. Suuta jedhii sirriitti riguu. Yoo harka kee yaaluuf itti hin fayyadamne ta\'e, erga dibdee booda harka kee dhiqadhu.',
    pros: 'Dhukkubbii maashaa fi buusaa xixiqqoo yeroof akka salphatuuf gargaara. THC kan hin qabne yoo ta\'u, dafee gogaa keessa seenee saffisaan hojjeta.',
    cons: 'Fayyadama alaa qofaaf. Madaa yookiin gogaa miidhame irratti hin dibin. Ija kee irraa fageessi. Yoo haalli isaa hammaate yookiin mallattooleen guyyaa 7 ol turan, fayyadamuu dhaabii hakiima mariisisi.',
};


type VerificationStatus = 'verified' | 'unknown';

export default function ScanMedicinePage() {
  const [imageDataUri, setImageDataUri] = useState<string | null>(null);
  const [isProcessing, setIsProcessing] = useState(false);
  const [verificationStatus, setVerificationStatus] = useState<VerificationStatus | null>(null);
  const [aiResult, setAiResult] = useState<AnalyzeMedicinePackageOutput | null>(null);
  
  const fileInputRef = useRef<HTMLInputElement>(null);
  const { toast } = useToast();
  const { getTranslation, language } = useLanguage();

  const translations = useMemo(() => ({
    scanTitle: { en: 'Scan Your Medicine', am: 'መድሃኒትዎን ይቃኙ', om: 'Qoricha Keessan Iskaan Godhaa' },
    scanDescription: { en: 'Upload or capture an image of the medicine package.', am: 'የመድሃኒቱን ፓኬጅ ፎቶ ይስቀሉ ወይም ያንሱ።', om: 'Suuraa paakeejii qorichaa olkaa\'aa yookiin kaasaa.' },
    uploadButton: { en: 'Upload Image', am: 'ምስል ስቀል', om: 'Suura Olkaa\'i' },
    cameraButton: { en: 'Use Camera', am: 'ካሜራ ተጠቀም', om: 'Kaameraa Fayyadami' },
    scanResultTitle: { en: 'Scan Result', am: 'የፍተሻ ውጤት', om: 'Bu\'aa Iskaanii' },
    capturedImageTitle: { en: 'Captured Image', am: 'የተነሳ ምስል', om: 'Suura Kaafame' },
    analyzingText: { en: 'Analyzing your medicine...', am: 'መድሃኒትዎን በመተንተን ላይ...', om: 'Qoricha keessan qaaccessaa jira...' },
    takeAMomentText: { en: 'This may take a moment.', am: 'ይህ የተወሰነ ጊዜ ሊወስድ ይችላል።', om: 'Kun yeroo muraasa fudhachuu danda\'a.' },
    verifiedTitle: { en: 'Verified', am: 'የተረጋገጠ', om: 'Mirkanaa\'e' },
    matchFoundText: { en: 'Match found for', am: 'ተዛማጅ ተገኝቷል ለ', om: 'Walsimsi argameera' },
    aiSummaryTitle: { en: 'AI Summary', am: 'የ AI ማጠቃለያ', om: 'Cuunfaa AI' },
    generatedForText: { en: 'Generated by IDA for', am: 'በIDA የተፈጠረ ለ', om: 'IDA tiin kan uumame' },
    howToTake: { en: 'How to Take', am: 'እንዴት እንደሚወሰድ', om: 'Akkaataa Fudhatiinsaa' },
    pros: { en: 'Pros / Benefits', am: 'ጥቅሞች', om: 'Faayidaa' },
    cons: { en: 'Cons / Side Effects', am: 'ጉዳቶች / የጎንዮሽ ጉዳቶች', om: 'Miidhaa / Miidhaa Ganaa' },
    disclaimerTitle: { en: 'Disclaimer', am: 'የኃላፊነት ማስተባበያ', om: 'Of-gaafii' },
    disclaimerText: { en: 'This is for informational purposes only. Always consult a qualified healthcare professional before making any medical decisions.', am: 'ይህ ለመረጃ አገልግሎት ብቻ ነው። ማንኛውንም የህክምና ውሳኔ ከማድረግዎ በፊት ሁል ጊዜ ብቃት ያለው የጤና ባለሙያ ያማክሩ።', om: 'Kun kaayyoo odeeffannootiif qofa. Murtii yaalaa kamiyyuu gochuu keessan dura yeroo hunda ogeessa fayyaa gahumsa qabu mariisisaa.' },
  }), [language]);

  const resetState = () => {
    setImageDataUri(null);
    setIsProcessing(false);
    setVerificationStatus(null);
    setAiResult(null);
    if(fileInputRef.current) {
      fileInputRef.current.value = '';
    }
  };

  const handleImageChange = (file: File) => {
    if (!file) return;
    resetState();
    const reader = new FileReader();
    reader.onload = (e) => {
      const dataUri = e.target?.result as string;
      setImageDataUri(dataUri);
      processImage(dataUri);
    };
    reader.readAsDataURL(file);
  };

  const handleFileSelect = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) {
      handleImageChange(file);
    }
  };

  const processImage = async (dataUri: string) => {
    setIsProcessing(true);
    setAiResult(null);

    await new Promise(resolve => setTimeout(resolve, 2500));
    
    let result: AnalyzeMedicinePackageOutput;
    switch (language) {
      case 'am':
        result = demoResultAm;
        break;
      case 'om':
        result = demoResultOm;
        break;
      default:
        result = demoResultEn;
    }
    
    setVerificationStatus('verified');
    setAiResult(result);
    setIsProcessing(false);
  };

  if (!imageDataUri) {
    return (
      <div className="flex flex-col items-center justify-center h-full p-4 md:p-6 bg-background">
        <Card className="w-full max-w-md text-center">
          <CardHeader>
            <CardTitle className="font-headline text-3xl">{getTranslation(translations.scanTitle)}</CardTitle>
            <CardDescription>{getTranslation(translations.scanDescription)}</CardDescription>
          </CardHeader>
          <CardContent className="flex flex-col gap-4">
             <input type="file" ref={fileInputRef} onChange={handleFileSelect} className="hidden" accept="image/*" />
            <Button size="lg" onClick={() => fileInputRef.current?.click()}>
              <Upload className="mr-2 h-5 w-5" />
              {getTranslation(translations.uploadButton)}
            </Button>
            <input type="file" id="camera-input" onChange={handleFileSelect} className="hidden" accept="image/*" capture="environment" />
            <Button size="lg" variant="outline" onClick={() => document.getElementById('camera-input')?.click()}>
              <Camera className="mr-2 h-5 w-5" />
               {getTranslation(translations.cameraButton)}
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="p-4 md:p-6 space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="font-headline text-3xl">{getTranslation(translations.scanResultTitle)}</h1>
        <Button variant="ghost" size="icon" onClick={resetState}><X/></Button>
      </div>
      
      <div className="grid md:grid-cols-2 gap-6 items-start">
        <Card>
          <CardHeader>
            <CardTitle>{getTranslation(translations.capturedImageTitle)}</CardTitle>
          </CardHeader>
          <CardContent>
             <div className="relative overflow-hidden rounded-lg">
                <Image src={imageDataUri} alt="Medicine Package" width={500} height={500} className="w-full h-auto" />
                {isProcessing && <div className="scan-animation"></div>}
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          {isProcessing && !aiResult ? (
            <Card>
              <CardContent className="pt-6 flex flex-col items-center justify-center text-center">
                  <Wand2 className="h-10 w-10 animate-pulse text-primary" />
                  <p className="mt-4 text-muted-foreground font-semibold">{getTranslation(translations.analyzingText)}</p>
                  <p className="mt-1 text-sm text-muted-foreground">{getTranslation(translations.takeAMomentText)}</p>
              </CardContent>
            </Card>
          ) : (
            <>
              {verificationStatus === 'verified' && aiResult && (
                  <Alert variant="default" className="bg-green-100 dark:bg-green-900/50 border-green-500">
                    <ShieldCheck className="h-5 w-5 text-green-600 dark:text-green-400" />
                    <AlertTitle className="text-green-800 dark:text-green-300">{getTranslation(translations.verifiedTitle)}</AlertTitle>
                    <AlertDescription className="text-green-700 dark:text-green-400">
                      {getTranslation(translations.matchFoundText)} "{aiResult.name}".
                    </AlertDescription>
                  </Alert>
              )}
              
              {aiResult && (
                 <Card className="bg-card">
                    <CardHeader>
                        <CardTitle className="flex items-center gap-2 font-headline text-2xl">
                            <Wand2 /> {getTranslation(translations.aiSummaryTitle)}
                        </CardTitle>
                        <CardDescription>{getTranslation(translations.generatedForText)} "{aiResult.name}"</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-6">
                        <div className="flex items-start gap-4">
                            <div className="p-2 bg-blue-100 dark:bg-blue-900/50 rounded-full">
                                <Info className="h-5 w-5 text-blue-600 dark:text-blue-400" />
                            </div>
                            <div>
                                <h3 className="font-bold text-foreground">{getTranslation(translations.howToTake)}</h3>
                                <p className="text-muted-foreground">{aiResult.usage}</p>
                            </div>
                        </div>
                         <div className="flex items-start gap-4">
                            <div className="p-2 bg-green-100 dark:bg-green-900/50 rounded-full">
                               <CheckCircle className="h-5 w-5 text-green-600 dark:text-green-400" />
                            </div>
                            <div>
                                <h3 className="font-bold text-foreground">{getTranslation(translations.pros)}</h3>
                                <p className="text-muted-foreground">{aiResult.pros}</p>
                            </div>
                        </div>
                         <div className="flex items-start gap-4">
                            <div className="p-2 bg-red-100 dark:bg-red-900/50 rounded-full">
                                <XCircle className="h-5 w-5 text-red-600 dark:text-red-400" />
                            </div>
                            <div>
                                <h3 className="font-bold text-foreground">{getTranslation(translations.cons)}</h3>
                                <p className="text-muted-foreground">{aiResult.cons}</p>
                            </div>
                        </div>
                    </CardContent>
                 </Card>
              )}

              <Alert variant="default" className="mt-4 border-amber-500 bg-amber-50 dark:bg-amber-950">
                <AlertTriangle className="h-5 w-5 text-amber-600 dark:text-amber-400" />
                <AlertTitle className="text-amber-800 dark:text-amber-300">{getTranslation(translations.disclaimerTitle)}</AlertTitle>
                <AlertDescription className="text-amber-700 dark:text-amber-500">
                  {getTranslation(translations.disclaimerText)}
                </AlertDescription>
              </Alert>
            </>
          )}
        </div>
      </div>
    </div>
  );
}
